# Generated by Django 4.2.7 on 2025-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('numOfReviews', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
